using Echo.Core.Mapping.MemberMapping;
using Echo.Core.Tests.TestData.Factories;

namespace Echo.Core.Tests.Mapping.MemberMapping;

[Trait("Category", "Unit")]
public class MemberMapperTests
{
    private readonly IMemberMapper _mapper = new MemberMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = MemberFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(dto.FirstName, entity.FirstName);
        Assert.Equal(dto.LastName, entity.LastName);
        Assert.Equal(dto.OtherNames, entity.OtherNames);
        Assert.Equal(dto.EmailAddress, entity.EmailAddress);
        Assert.Equal(dto.PhoneNumber, entity.PhoneNumber);
        Assert.Equal(dto.DateOfBirth, entity.DateOfBirth);
        Assert.Equal(dto.JoinedDate, entity.JoinedDate);
        Assert.Equal(dto.Gender, entity.Gender);
        Assert.Equal(dto.ResidentialAddress, entity.ResidentialAddress);
        Assert.Equal(dto.City, entity.City);
        Assert.Equal(dto.Hometown, entity.Hometown);
        Assert.Equal(dto.Region, entity.Region);
        Assert.Equal(dto.GpsAddress, entity.GpsAddress);
        Assert.Equal(dto.MaritalStatus, entity.MaritalStatus);
        Assert.Equal(dto.NextOfKin, entity.NextOfKin);
        Assert.Equal(dto.EmergencyContactName, entity.EmergencyContactName);
        Assert.Equal(dto.EmergencyContactPhoneNumber, entity.EmergencyContactPhoneNumber);
        Assert.Equal(dto.MemberActivityStatus, entity.MemberActivityStatus);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = MemberFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, entity.Id);
        Assert.Equal(Guid.Empty, entity.CongregationId);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = MemberFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.FirstName, result.FirstName);
        Assert.Equal(entity.LastName, result.LastName);
        Assert.Equal(entity.OtherNames, result.OtherNames);
        Assert.Equal(entity.EmailAddress, result.EmailAddress);
        Assert.Equal(entity.PhoneNumber, result.PhoneNumber);
        Assert.Equal(entity.DateOfBirth, result.DateOfBirth);
        Assert.Equal(entity.JoinedDate, result.JoinedDate);
        Assert.Equal(entity.Gender, result.Gender);
        Assert.Equal(entity.ResidentialAddress, result.ResidentialAddress);
        Assert.Equal(entity.City, result.City);
        Assert.Equal(entity.Hometown, result.Hometown);
        Assert.Equal(entity.Region, result.Region);
        Assert.Equal(entity.GpsAddress, result.GpsAddress);
        Assert.Equal(entity.MaritalStatus, result.MaritalStatus);
        Assert.Equal(entity.NextOfKin, result.NextOfKin);
        Assert.Equal(entity.EmergencyContactName, result.EmergencyContactName);
        Assert.Equal(entity.EmergencyContactPhoneNumber, result.EmergencyContactPhoneNumber);
        Assert.Equal(entity.MemberActivityStatus, result.MemberActivityStatus);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void PatchEntity_ShouldPatchSpecifiedFieldsInDto_ToEntity()
    {
        var dto = MemberFactory.NewUpdateDto();
        var entity = MemberFactory.NewEntity();

        _mapper.Patch(dto, entity);

        Assert.Equal(dto.FirstName, entity.FirstName);
        Assert.Equal(dto.LastName, entity.LastName);
        Assert.Equal(dto.OtherNames, entity.OtherNames);
        Assert.Equal(dto.EmailAddress, entity.EmailAddress);
        Assert.Equal(dto.PhoneNumber, entity.PhoneNumber);
        Assert.Equal(dto.DateOfBirth, entity.DateOfBirth);
        Assert.Equal(dto.JoinedDate, entity.JoinedDate);
        Assert.Equal(dto.Gender, entity.Gender);
        Assert.Equal(dto.ResidentialAddress, entity.ResidentialAddress);
        Assert.Equal(dto.City, entity.City);
        Assert.Equal(dto.Hometown, entity.Hometown);
        Assert.Equal(dto.Region, entity.Region);
        Assert.Equal(dto.GpsAddress, entity.GpsAddress);
        Assert.Equal(dto.MaritalStatus, entity.MaritalStatus);
        Assert.Equal(dto.NextOfKin, entity.NextOfKin);
        Assert.Equal(dto.EmergencyContactName, entity.EmergencyContactName);
        Assert.Equal(dto.EmergencyContactPhoneNumber, entity.EmergencyContactPhoneNumber);
        Assert.Equal(dto.MemberActivityStatus, entity.MemberActivityStatus);
    }

    [Fact]
    public void PatchEntity_ShouldIgnoreAllNullFieldsInDto()
    {
        var nullDto = MemberFactory.NewUpdateDtoWithNullValues();
        var entity = MemberFactory.NewEntity();
        var original = MemberFactory.NewEntity();

        _mapper.Patch(nullDto, entity);

        Assert.Equal(original.FirstName, entity.FirstName);
        Assert.Equal(original.LastName, entity.LastName);
        Assert.Equal(original.OtherNames, entity.OtherNames);
        Assert.Equal(original.EmailAddress, entity.EmailAddress);
        Assert.Equal(original.PhoneNumber, entity.PhoneNumber);
        Assert.Equal(original.DateOfBirth, entity.DateOfBirth);
        Assert.Equal(original.JoinedDate, entity.JoinedDate);
        Assert.Equal(original.Gender, entity.Gender);
        Assert.Equal(original.ResidentialAddress, entity.ResidentialAddress);
        Assert.Equal(original.City, entity.City);
        Assert.Equal(original.Hometown, entity.Hometown);
        Assert.Equal(original.Region, entity.Region);
        Assert.Equal(original.GpsAddress, entity.GpsAddress);
        Assert.Equal(original.MaritalStatus, entity.MaritalStatus);
        Assert.Equal(original.NextOfKin, entity.NextOfKin);
        Assert.Equal(original.EmergencyContactName, entity.EmergencyContactName);
        Assert.Equal(original.EmergencyContactPhoneNumber, entity.EmergencyContactPhoneNumber);
        Assert.Equal(original.MemberActivityStatus, entity.MemberActivityStatus);
    }

    [Fact]
    public void ToSearchDto_ShouldMapFields_FromEntityList()
    {
        var entityList = MemberFactory.NewEntityList();
        var dtoList = _mapper.ToSearchDto(entityList);

        var firstEntity = entityList.First();
        var firstDto = dtoList.First();

        var lastEntity = entityList.Last();
        var lastDto = dtoList.Last();

        Assert.Equal(firstEntity.Id, firstDto.Id);
        Assert.Equal(firstEntity.Name, firstDto.Name);

        Assert.Equal(lastEntity.Id, lastDto.Id);
        Assert.Equal(lastEntity.Name, lastDto.Name);
    }
}
