---
services:
  api:
    build:
      context: .
      dockerfile: backend/src/Echo.Api/Dockerfile
    environment:
      Database__Host: db
      Database__Port: ${DB_PORT}
      Database__Name: ${DB_NAME}
      Database__Username: ${DB_USERNAME}
      Database__Password: ${DB_PASSWORD}
      Jwt__PrivateKey: ${JWT_PRIVATE_KEY}
      Jwt__PublicKey: ${JWT_PUBLIC_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      FrontendClient__BaseUrl: ${FRONTEND_BASE_URL}
      MailClient__Address: ${MAIL_CLIENT_ADDRESS}
      Resend__ApiKey: ${RESEND_API_KEY}
      RunMigrationsOnStartup: ${RUN_DATABASE_MIGRATIONS_ON_STARTUP}
    healthcheck:
      test: [CMD, curl, -f, http://localhost:8080/api/health/live]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
    networks: [echo-network]
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./infra/postgres/init/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql
      - ./infra/postgres/backup/db_dumps:/db_dumps:ro
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [echo-network]
  nginx:
    image: nginx:latest
    volumes: [./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro]
    depends_on:
      api:
        condition: service_healthy
    networks: [echo-network]
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy
    networks: [echo-network]
  backup:
    build:
      context: .
      dockerfile: infra/postgres/backup/Dockerfile
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      PGPASSWORD: ${DB_PASSWORD}
    volumes:
      - ./infra/postgres/backup/backup.sh:/backup.sh:ro
      - ./infra/postgres/backup/db_dumps:/db_dumps
    # Entry point is defined per environment in override/prod files
    # Since schedule differs between dev and prod
    depends_on:
      db:
        condition: service_healthy
    networks: [echo-network]
    profiles: [db-tools]
    restart: unless-stopped
  migrator:
    build:
      context: .
      target: build
      dockerfile: backend/src/Echo.Api/Dockerfile
    environment:
      Database__Host: db
      Database__Port: 5432
      Database__Name: ${DB_NAME}
      Database__Username: ${DB_USERNAME}
      Database__Password: ${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Development
    entrypoint:
      - sh
      - -c
      - dotnet tool restore && dotnet ef database update --project src/Echo.Infrastructure
    depends_on:
      db:
        condition: service_healthy
    networks: [echo-network]
    profiles: [db-tools]
networks:
  echo-network:
volumes:
  postgres-data:
