---
services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: 'true'
    volumes:
      - /build/src/Echo.Api/bin
      - /build/src/Echo.Api/obj
      - /build/src/Echo.Application/bin
      - /build/src/Echo.Application/obj
      - /build/src/Echo.Auth/bin
      - /build/src/Echo.Auth/obj
      - /build/src/Echo.Shared/bin
      - /build/src/Echo.Shared/obj
      - /build/src/Echo.Domain/bin
      - /build/src/Echo.Domain/obj
      - /build/src/Echo.Data/bin
      - /build/src/Echo.Data/obj
      - /build/src/Echo.ServiceDefaults/obj
      - /build/src/Echo.ServiceDefaults/bin
      - nuget-cache:/root/.nuget/packages
    ports: [5025:5025]
  db:
    ports: [5432:5432]
  nginx:
    ports: [8080:80]
  client:
    build:
      target: deps
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes: [./frontend:/app, /app/node_modules]
    ports: [5173:5173]
volumes:
  nuget-cache:
