---
services:
  api:
    build:
      target: build
    working_dir: /src
    command: dotnet run --project backend/src/Echo.Api/Echo.Api.csproj --urls http://0.0.0.0:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: 'true'
    volumes:
      - ./backend:/src/backend
      - /src/backend/src/Echo.Api/bin
      - /src/backend/src/Echo.Api/obj
      - /src/backend/src/Echo.Application/bin
      - /src/backend/src/Echo.Application/obj
      - /src/backend/src/Echo.Auth/bin
      - /src/backend/src/Echo.Auth/obj
      - /src/backend/src/Echo.Core/bin
      - /src/backend/src/Echo.Core/obj
      - /src/backend/src/Echo.Domain/bin
      - /src/backend/src/Echo.Domain/obj
      - /src/backend/src/Echo.Infrastructure/bin
      - /src/backend/src/Echo.Infrastructure/obj
      - nuget-cache:/root/.nuget/packages
    ports: [5025:8080]
  db:
    ports: [5432:5432]
  nginx:
    ports: [8080:80]
  client:
    build:
      target: deps
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes: [./frontend:/app, /app/node_modules]
    ports: [5173:5173]
volumes:
  nuget-cache:
