<Project Sdk="Aspire.AppHost.Sdk/13.5.4">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>1614bb0d-7ff5-439c-bd22-8ac6ffd57934</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Echo.Api\Echo.Api.csproj" />
    <ProjectReference Include="..\Echo.MigrationService\Echo.MigrationService.csproj" />
  </ItemGroup>
</Project>
