using Echo.Core.Mapping.OrganizationMapping;
using Echo.Core.Tests.TestData.Factories;

namespace Echo.Core.Tests.Mapping.OrganizationMapping;

[Trait("Category", "Unit")]
public class OrganizationMapperTests
{
    private readonly IOrganizationMapper _mapper = new OrganizationMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = OrganizationFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(dto.Name, entity.Name);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = OrganizationFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, entity.Id);
        Assert.Equal(Guid.Empty, entity.CongregationId);
        Assert.Null(entity.Congregation);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = OrganizationFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.Name, result.Name);
        Assert.Equal(entity.Description, result.Description);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void PatchEntity_ShouldPatchSpecifiedFieldsInDto_ToEntity()
    {
        var dto = OrganizationFactory.NewUpdateDto();
        var entity = OrganizationFactory.NewEntity();

        _mapper.Patch(dto, entity);

        Assert.Equal(dto.Name, entity.Name);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void PatchEntity_ShouldIgnoreAllNullFieldsInDto()
    {
        var nullDto = OrganizationFactory.NewUpdateDtoWithNullValues();
        var entity = OrganizationFactory.NewEntity();
        var original = OrganizationFactory.NewEntity();

        _mapper.Patch(nullDto, entity);

        Assert.Equal(original.Name, entity.Name);
        Assert.Equal(original.Description, entity.Description);
    }

    [Fact]
    public void ToSearchDto_ShouldMapFields_FromEntityList()
    {
        var entityList = OrganizationFactory.NewEntityList();
        var dtoList = _mapper.ToSearchDto(entityList);

        var firstEntity = entityList.First();
        var firstDto = dtoList.First();

        var lastEntity = entityList.Last();
        var lastDto = dtoList.Last();

        Assert.Equal(firstEntity.Id, firstDto.Id);
        Assert.Equal(firstEntity.Name, firstDto.Name);

        Assert.Equal(lastEntity.Id, lastDto.Id);
        Assert.Equal(lastEntity.Name, lastDto.Name);
    }
}
