using Echo.Core.Mapping.ProjectContributionMapping;
using Echo.Core.Tests.TestData.Factories;

namespace Echo.Core.Tests.Mapping.ProjectContributionMapping;

[Trait("Category", "Unit")]
public class ProjectContributionMapperTests
{
    private readonly IProjectContributionMapper _mapper = new ProjectContributionMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = ProjectContributionFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(dto.ProjectId, entity.ProjectId);
        Assert.Equal(dto.Amount, entity.Amount);
        Assert.Equal(dto.DateContributed, entity.DateContributed);
        Assert.Equal(dto.PaymentMethod, entity.PaymentMethod);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = ProjectContributionFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, entity.Id);
        Assert.Equal(Guid.Empty, entity.CongregationId);
        Assert.Null(entity.Congregation);
        Assert.Null(entity.Project);
        Assert.Equal(default, entity.CreatedAt);
        Assert.Null(entity.DeletedAt);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = ProjectContributionFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.ProjectId, result.ProjectId);
        Assert.Equal(entity.Project.Name, result.ProjectName);
        Assert.Equal(entity.Amount, result.Amount);
        Assert.Equal(entity.DateContributed, result.DateContributed);
        Assert.Equal(entity.PaymentMethod, result.PaymentMethod);
        Assert.Equal(entity.Description, result.Description);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void PatchEntity_ShouldPatchSpecifiedFieldsInDto_ToEntity()
    {
        var dto = ProjectContributionFactory.NewUpdateDto();
        var entity = ProjectContributionFactory.NewEntity();

        _mapper.Patch(dto, entity);

        Assert.Equal(dto.Amount, entity.Amount);
        Assert.Equal(dto.DateContributed, entity.DateContributed);
        Assert.Equal(dto.PaymentMethod, entity.PaymentMethod);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void PatchEntity_ShouldIgnoreAllNullFieldsInDto()
    {
        var nullDto = ProjectContributionFactory.NewUpdateDtoWithNullValues();
        var entity = ProjectContributionFactory.NewEntity();
        var original = ProjectContributionFactory.NewEntity();

        _mapper.Patch(nullDto, entity);

        Assert.Equal(original.Amount, entity.Amount);
        Assert.Equal(original.DateContributed, entity.DateContributed);
        Assert.Equal(original.PaymentMethod, entity.PaymentMethod);
        Assert.Equal(original.Description, entity.Description);
    }
}
