using Echo.Core.Mapping.ProjectMapping;
using Echo.Core.Tests.TestData.Factories;

namespace Echo.Core.Tests.Mapping.ProjectMapping;

[Trait("Category", "Unit")]
public class ProjectMapperTests
{
    private readonly IProjectMapper _mapper = new ProjectMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = ProjectFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(dto.CategoryId, entity.CategoryId);
        Assert.Equal(dto.ManagerId, entity.ManagerId);
        Assert.Equal(dto.Name, entity.Name);
        Assert.Equal(dto.TargetAmount, entity.TargetAmount);
        Assert.Equal(dto.Status, entity.Status);
        Assert.Equal(dto.StartDate, entity.StartDate);
        Assert.Equal(dto.EndDate, entity.EndDate);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = ProjectFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, entity.Id);
        Assert.Equal(Guid.Empty, entity.CongregationId);
        Assert.Null(entity.Congregation);
        Assert.Null(entity.Category);
        Assert.Null(entity.Manager);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = ProjectFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.CategoryId, result.CategoryId);
        Assert.Equal(entity.Category.Name, result.CategoryName);
        Assert.Equal(entity.ManagerId, result.ManagerId);
        Assert.Equal(entity.Manager.Name, result.ManagerName);
        Assert.Equal(entity.Name, result.Name);
        Assert.Equal(entity.TargetAmount, result.TargetAmount);
        Assert.Equal(entity.Status, result.Status);
        Assert.Equal(entity.StartDate, result.StartDate);
        Assert.Equal(entity.EndDate, result.EndDate);
        Assert.Equal(entity.Description, result.Description);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void PatchEntity_ShouldPatchSpecifiedFieldsInDto_ToEntity()
    {
        var dto = ProjectFactory.NewUpdateDto();
        var entity = ProjectFactory.NewEntity();

        _mapper.Patch(dto, entity);

        Assert.Equal(dto.CategoryId, entity.CategoryId);
        Assert.Equal(dto.ManagerId, entity.ManagerId);
        Assert.Equal(dto.Name, entity.Name);
        Assert.Equal(dto.TargetAmount, entity.TargetAmount);
        Assert.Equal(dto.Status, entity.Status);
        Assert.Equal(dto.StartDate, entity.StartDate);
        Assert.Equal(dto.EndDate, entity.EndDate);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void PatchEntity_ShouldIgnoreAllNullFieldsInDto()
    {
        var nullDto = ProjectFactory.NewUpdateDtoWithNullValues();
        var entity = ProjectFactory.NewEntity();
        var original = ProjectFactory.NewEntity();

        _mapper.Patch(nullDto, entity);

        Assert.Equal(original.CategoryId, entity.CategoryId);
        Assert.Equal(original.ManagerId, entity.ManagerId);
        Assert.Equal(original.Name, entity.Name);
        Assert.Equal(original.TargetAmount, entity.TargetAmount);
        Assert.Equal(original.Status, entity.Status);
        Assert.Equal(original.StartDate, entity.StartDate);
        Assert.Equal(original.EndDate, entity.EndDate);
        Assert.Equal(original.Description, entity.Description);
    }
}
