using Echo.Core.Mapping.UserMapping;
using Echo.Core.Tests.TestData.Factories;

namespace Echo.Core.Tests.Mapping.UserMapping;

[Trait("Category", "Unit")]
public class UserMapperTests
{
    private readonly IUserMapper _mapper = new UserMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = UserFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(dto.FirstName, entity.FirstName);
        Assert.Equal(dto.LastName, entity.LastName);
        Assert.Equal(dto.OtherNames, entity.OtherNames);
        Assert.Equal(dto.EmailAddress, entity.EmailAddress);
        Assert.Equal(dto.Password, entity.PasswordHash);
        Assert.Equal(dto.Role, entity.Role);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = UserFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, entity.Id);
        Assert.Equal(Guid.Empty, entity.CongregationId);
        Assert.Null(entity.Congregation);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = UserFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.EmailAddress, result.EmailAddress);
        Assert.Equal(entity.Role, result.Role);
        Assert.Equal(entity.EmailVerifiedAt, result.VerifiedAt);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void PatchEntity_ShouldPatchSpecifiedFieldsInDto_ToEntity()
    {
        var dto = UserFactory.NewUpdateDto();
        var entity = UserFactory.NewEntity();

        _mapper.Patch(dto, entity);

        Assert.Equal(dto.EmailAddress, entity.EmailAddress);
        Assert.Equal(dto.Password, entity.PasswordHash);
        Assert.Equal(dto.Role, entity.Role);
    }

    [Fact]
    public void PatchEntity_ShouldIgnoreAllNullFieldsInDto()
    {
        var nullDto = UserFactory.NewUpdateDtoWithNullValues();
        var entity = UserFactory.NewEntity();
        var original = UserFactory.NewEntity();

        _mapper.Patch(nullDto, entity);

        Assert.Equal(original.EmailAddress, entity.EmailAddress);
        Assert.Equal(original.PasswordHash, entity.PasswordHash);
        Assert.Equal(original.Role, entity.Role);
    }
}
