using Echo.Core.Mapping.TransactionMapping;
using Echo.Core.Tests.TestData.Factories;

namespace Echo.Core.Tests.Mapping.TransactionMapping;

[Trait("Category", "Unit")]
public class TransactionMapperTests
{
    private readonly ITransactionMapper _mapper = new TransactionMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = TransactionFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(dto.CategoryId, entity.CategoryId);
        Assert.Equal(dto.TransactionType, entity.TransactionType);
        Assert.Equal(dto.TransactionDate, entity.TransactionDate);
        Assert.Equal(dto.Amount, entity.Amount);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = TransactionFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, entity.Id);
        Assert.Equal(Guid.Empty, entity.CongregationId);
        Assert.Null(entity.Congregation);
        Assert.Null(entity.Category);
        Assert.Equal(default, entity.CreatedAt);
        Assert.Null(entity.DeletedAt);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = TransactionFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.CategoryId, result.CategoryId);
        Assert.Equal(entity.Category.Name, result.CategoryName);
        Assert.Equal(entity.TransactionType, result.TransactionType);
        Assert.Equal(entity.TransactionDate, result.TransactionDate);
        Assert.Equal(entity.Amount, result.Amount);
        Assert.Equal(entity.Description, result.Description);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void PatchEntity_ShouldPatchSpecifiedFieldsInDto_ToEntity()
    {
        var dto = TransactionFactory.NewUpdateDto();
        var entity = TransactionFactory.NewEntity();

        _mapper.Patch(dto, entity);

        Assert.Equal(dto.CategoryId, entity.CategoryId);
        Assert.Equal(dto.TransactionType, entity.TransactionType);
        Assert.Equal(dto.TransactionDate, entity.TransactionDate);
        Assert.Equal(dto.Amount, entity.Amount);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void PatchEntity_ShouldIgnoreAllNullFieldsInDto()
    {
        var nullDto = TransactionFactory.NewUpdateDtoWithNullValues();
        var entity = TransactionFactory.NewEntity();
        var original = TransactionFactory.NewEntity();

        _mapper.Patch(nullDto, entity);

        Assert.Equal(original.CategoryId, entity.CategoryId);
        Assert.Equal(original.TransactionType, entity.TransactionType);
        Assert.Equal(original.TransactionDate, entity.TransactionDate);
        Assert.Equal(original.Amount, entity.Amount);
        Assert.Equal(original.Description, entity.Description);
    }
}
