using Echo.Core.Mapping.EventMapping;
using Echo.Core.Tests.TestData.Factories;

namespace Echo.Core.Tests.Mapping.EventMapping;

[Trait("Category", "Unit")]
public class EventMapperTests
{
    private readonly IEventMapper _mapper = new EventMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = EventFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(dto.OrganizationId, entity.OrganizationId);
        Assert.Equal(dto.OrganizerId, entity.OrganizerId);
        Assert.Equal(dto.Name, entity.Name);
        Assert.Equal(dto.StartDate, entity.StartDate);
        Assert.Equal(dto.EndDate, entity.EndDate);
        Assert.Equal(dto.StartTime, entity.StartTime);
        Assert.Equal(dto.EndTime, entity.EndTime);
        Assert.Equal(dto.Location, entity.Location);
        Assert.Equal(dto.Capacity, entity.Capacity);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = EventFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, entity.Id);
        Assert.Equal(Guid.Empty, entity.CongregationId);
        Assert.Null(entity.Congregation);
        Assert.Null(entity.Organization);
        Assert.Null(entity.Organizer);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = EventFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.OrganizationId, result.OrganizationId);
        Assert.Equal(entity.Organization.Name, result.OrganizationName);
        Assert.Equal(entity.OrganizerId, result.OrganizerId);
        Assert.Equal(entity.Organizer.Name, result.OrganizerName);
        Assert.Equal(entity.Name, result.Name);
        Assert.Equal(entity.StartDate, result.StartDate);
        Assert.Equal(entity.EndDate, result.EndDate);
        Assert.Equal(entity.StartTime, result.StartTime);
        Assert.Equal(entity.EndTime, result.EndTime);
        Assert.Equal(entity.Location, result.Location);
        Assert.Equal(entity.Capacity, result.Capacity);
        Assert.Equal(entity.Description, result.Description);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void PatchEntity_ShouldPatchSpecifiedFieldsInDto_ToEntity()
    {
        var dto = EventFactory.NewUpdateDto();
        var entity = EventFactory.NewEntity();

        _mapper.Patch(dto, entity);

        Assert.Equal(dto.OrganizationId, entity.OrganizationId);
        Assert.Equal(dto.OrganizerId, entity.OrganizerId);
        Assert.Equal(dto.Name, entity.Name);
        Assert.Equal(dto.StartDate, entity.StartDate);
        Assert.Equal(dto.EndDate, entity.EndDate);
        Assert.Equal(dto.StartTime, entity.StartTime);
        Assert.Equal(dto.EndTime, entity.EndTime);
        Assert.Equal(dto.Location, entity.Location);
        Assert.Equal(dto.Capacity, entity.Capacity);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void PatchEntity_ShouldIgnoreAllNullFieldsInDto()
    {
        var nullDto = EventFactory.NewUpdateDtoWithNullValues();
        var entity = EventFactory.NewEntity();
        var original = EventFactory.NewEntity();

        _mapper.Patch(nullDto, entity);

        Assert.Equal(original.OrganizationId, entity.OrganizationId);
        Assert.Equal(original.OrganizerId, entity.OrganizerId);
        Assert.Equal(original.Name, entity.Name);
        Assert.Equal(original.StartDate, entity.StartDate);
        Assert.Equal(original.EndDate, entity.EndDate);
        Assert.Equal(original.StartTime, entity.StartTime);
        Assert.Equal(original.EndTime, entity.EndTime);
        Assert.Equal(original.Location, entity.Location);
        Assert.Equal(original.Capacity, entity.Capacity);
        Assert.Equal(original.Description, entity.Description);
    }
}
