using Echo.Application.Members;

namespace Echo.Application.Tests.Members;

[Trait("Category", "Unit")]
public class MemberMapperTests
{
    private readonly IMemberMapper _mapper = new MemberMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = MemberFactory.NewCreateDto();

        var (person, member) = _mapper.ToEntity(dto);

        // Person fields
        Assert.Equal(dto.FirstName, person.FirstName);
        Assert.Equal(dto.LastName, person.LastName);
        Assert.Equal(dto.OtherNames, person.OtherNames);
        Assert.Equal(dto.EmailAddress, person.EmailAddress);
        Assert.Equal(dto.PhoneNumber, person.PhoneNumber);

        // Member fields
        Assert.Equal(dto.DateOfBirth, member.DateOfBirth);
        Assert.Equal(dto.JoinedDate, member.JoinedDate);
        Assert.Equal(dto.Gender, member.Gender);
        Assert.Equal(dto.ResidentialAddress, member.ResidentialAddress);
        Assert.Equal(dto.City, member.City);
        Assert.Equal(dto.Hometown, member.Hometown);
        Assert.Equal(dto.Region, member.Region);
        Assert.Equal(dto.GpsAddress, member.GpsAddress);
        Assert.Equal(dto.MaritalStatus, member.MaritalStatus);
        Assert.Equal(dto.NextOfKin, member.NextOfKin);
        Assert.Equal(dto.EmergencyContactName, member.EmergencyContactName);
        Assert.Equal(dto.EmergencyContactPhoneNumber, member.EmergencyContactPhoneNumber);
        Assert.Equal(dto.Status, member.Status);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = MemberFactory.NewCreateDto();

        var (person, member) = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, person.Id);
        Assert.Equal(Guid.Empty, person.CongregationId);
        Assert.Equal(Guid.Empty, member.PersonId);
        Assert.Equal(Guid.Empty, member.CongregationId);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = MemberFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.PersonId, result.Id);
        Assert.Equal(entity.Person.Name, result.Name);
        Assert.Equal(entity.Person.FirstName, result.FirstName);
        Assert.Equal(entity.Person.LastName, result.LastName);
        Assert.Equal(entity.Person.OtherNames, result.OtherNames);
        Assert.Equal(entity.Person.EmailAddress, result.EmailAddress);
        Assert.Equal(entity.Person.PhoneNumber, result.PhoneNumber);
        Assert.Equal(entity.DateOfBirth, result.DateOfBirth);
        Assert.Equal(entity.JoinedDate, result.JoinedDate);
        Assert.Equal(entity.Gender, result.Gender);
        Assert.Equal(entity.ResidentialAddress, result.ResidentialAddress);
        Assert.Equal(entity.City, result.City);
        Assert.Equal(entity.Hometown, result.Hometown);
        Assert.Equal(entity.Region, result.Region);
        Assert.Equal(entity.GpsAddress, result.GpsAddress);
        Assert.Equal(entity.MaritalStatus, result.MaritalStatus);
        Assert.Equal(entity.NextOfKin, result.NextOfKin);
        Assert.Equal(entity.EmergencyContactName, result.EmergencyContactName);
        Assert.Equal(entity.EmergencyContactPhoneNumber, result.EmergencyContactPhoneNumber);
        Assert.Equal(entity.Status, result.Status);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void Patch_ShouldUpdateAllFields_WhenDtoHasValues()
    {
        var dto = MemberFactory.NewUpdateDto();
        var entity = MemberFactory.NewEntity();

        _mapper.Patch(dto, entity.Person, entity);

        // Person fields
        Assert.Equal(dto.FirstName, entity.Person.FirstName);
        Assert.Equal(dto.LastName, entity.Person.LastName);
        Assert.Equal(dto.OtherNames, entity.Person.OtherNames);
        Assert.Equal(dto.EmailAddress, entity.Person.EmailAddress);
        Assert.Equal(dto.PhoneNumber, entity.Person.PhoneNumber);

        // Member fields
        Assert.Equal(dto.DateOfBirth, entity.DateOfBirth);
        Assert.Equal(dto.JoinedDate, entity.JoinedDate);
        Assert.Equal(dto.Gender, entity.Gender);
        Assert.Equal(dto.ResidentialAddress, entity.ResidentialAddress);
        Assert.Equal(dto.City, entity.City);
        Assert.Equal(dto.Hometown, entity.Hometown);
        Assert.Equal(dto.Region, entity.Region);
        Assert.Equal(dto.GpsAddress, entity.GpsAddress);
        Assert.Equal(dto.MaritalStatus, entity.MaritalStatus);
        Assert.Equal(dto.NextOfKin, entity.NextOfKin);
        Assert.Equal(dto.EmergencyContactName, entity.EmergencyContactName);
        Assert.Equal(dto.EmergencyContactPhoneNumber, entity.EmergencyContactPhoneNumber);
        Assert.Equal(dto.Status, entity.Status);
    }

    [Fact]
    public void Patch_ShouldIgnoreAllNullFields_WhenDtoFieldsAreNull()
    {
        var nullDto = MemberFactory.NewUpdateDtoWithNullValues();
        var entity = MemberFactory.NewEntity();
        var original = MemberFactory.NewEntity();

        _mapper.Patch(nullDto, entity.Person, entity);

        // Person fields preserved
        Assert.Equal(original.Person.FirstName, entity.Person.FirstName);
        Assert.Equal(original.Person.LastName, entity.Person.LastName);
        Assert.Equal(original.Person.OtherNames, entity.Person.OtherNames);
        Assert.Equal(original.Person.EmailAddress, entity.Person.EmailAddress);
        Assert.Equal(original.Person.PhoneNumber, entity.Person.PhoneNumber);

        // Member fields preserved
        Assert.Equal(original.DateOfBirth, entity.DateOfBirth);
        Assert.Equal(original.JoinedDate, entity.JoinedDate);
        Assert.Equal(original.Gender, entity.Gender);
        Assert.Equal(original.ResidentialAddress, entity.ResidentialAddress);
        Assert.Equal(original.City, entity.City);
        Assert.Equal(original.Hometown, entity.Hometown);
        Assert.Equal(original.Region, entity.Region);
        Assert.Equal(original.GpsAddress, entity.GpsAddress);
        Assert.Equal(original.MaritalStatus, entity.MaritalStatus);
        Assert.Equal(original.NextOfKin, entity.NextOfKin);
        Assert.Equal(original.EmergencyContactName, entity.EmergencyContactName);
        Assert.Equal(original.EmergencyContactPhoneNumber, entity.EmergencyContactPhoneNumber);
        Assert.Equal(original.Status, entity.Status);
    }

    [Fact]
    public void ToSearchDto_ShouldMapFields_FromEntityList()
    {
        var entityList = MemberFactory.NewEntityList();
        var dtoList = _mapper.ToSearchDto(entityList);

        var firstEntity = entityList.First();
        var firstDto = dtoList.First();

        var lastEntity = entityList.Last();
        var lastDto = dtoList.Last();

        Assert.Equal(firstEntity.PersonId, firstDto.Id);
        Assert.Equal(firstEntity.Person.Name, firstDto.Name);
        Assert.Equal(firstEntity.Person.PhoneNumber, firstDto.PhoneNumber);

        Assert.Equal(lastEntity.PersonId, lastDto.Id);
        Assert.Equal(lastEntity.Person.Name, lastDto.Name);
        Assert.Equal(lastEntity.Person.PhoneNumber, lastDto.PhoneNumber);
    }
}
