-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public."AssetCategories_Id_seq";

CREATE SEQUENCE public."AssetCategories_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."AttendanceContexts_Id_seq";

CREATE SEQUENCE public."AttendanceContexts_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."AttendanceTypes_Id_seq";

CREATE SEQUENCE public."AttendanceTypes_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."ProjectCategories_Id_seq";

CREATE SEQUENCE public."ProjectCategories_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."TransactionCategories_Id_seq";

CREATE SEQUENCE public."TransactionCategories_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public."Congregations" definition

-- Drop table

-- DROP TABLE public."Congregations";

CREATE TABLE public."Congregations" (
	"CongregationId" uuid DEFAULT uuidv7() NOT NULL,
	"Name" varchar(255) NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Congregations" PRIMARY KEY ("CongregationId")
);


-- public."__EFMigrationsHistory" definition

-- Drop table

-- DROP TABLE public."__EFMigrationsHistory";

CREATE TABLE public."__EFMigrationsHistory" (
	"MigrationId" varchar(150) NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


-- public."AssetCategories" definition

-- Drop table

-- DROP TABLE public."AssetCategories";

CREATE TABLE public."AssetCategories" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"CongregationId" uuid NOT NULL,
	"Name" varchar(255) NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_AssetCategories" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AssetCategories_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE
);
CREATE INDEX "IX_AssetCategories_CongregationId" ON public."AssetCategories" USING btree ("CongregationId");
CREATE UNIQUE INDEX "IX_AssetCategories_CongregationId_Name" ON public."AssetCategories" USING btree ("CongregationId", "Name");
CREATE INDEX "IX_AssetCategories_DeletedAt" ON public."AssetCategories" USING btree ("DeletedAt");


-- public."Assets" definition

-- Drop table

-- DROP TABLE public."Assets";

CREATE TABLE public."Assets" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"CategoryId" int4 NOT NULL,
	"Name" varchar(255) NOT NULL,
	"SerialNumber" varchar(255) NULL,
	"PurchaseDate" date NULL,
	"PurchaseCost" numeric NOT NULL,
	"CurrentValue" numeric NOT NULL,
	"Status" text NOT NULL,
	"Description" varchar(255) NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Assets" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Assets_AssetCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."AssetCategories"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_Assets_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE
);
CREATE INDEX "IX_Assets_CategoryId" ON public."Assets" USING btree ("CategoryId");
CREATE INDEX "IX_Assets_CongregationId" ON public."Assets" USING btree ("CongregationId");
CREATE INDEX "IX_Assets_DeletedAt" ON public."Assets" USING btree ("DeletedAt");


-- public."AttendanceTypes" definition

-- Drop table

-- DROP TABLE public."AttendanceTypes";

CREATE TABLE public."AttendanceTypes" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"CongregationId" uuid NOT NULL,
	"Name" varchar(255) NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_AttendanceTypes" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AttendanceTypes_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE
);
CREATE INDEX "IX_AttendanceTypes_CongregationId" ON public."AttendanceTypes" USING btree ("CongregationId");
CREATE UNIQUE INDEX "IX_AttendanceTypes_CongregationId_Name" ON public."AttendanceTypes" USING btree ("CongregationId", "Name");
CREATE INDEX "IX_AttendanceTypes_DeletedAt" ON public."AttendanceTypes" USING btree ("DeletedAt");


-- public."Members" definition

-- Drop table

-- DROP TABLE public."Members";

CREATE TABLE public."Members" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"Name" varchar(255) GENERATED ALWAYS AS (TRIM(BOTH FROM (((COALESCE("LastName", ''::character varying)::text || ' '::text) || COALESCE("FirstName", ''::character varying)::text) || ' '::text) || COALESCE("OtherNames", ''::character varying)::text)) STORED NOT NULL,
	"FirstName" varchar(255) NOT NULL,
	"LastName" varchar(255) NOT NULL,
	"OtherNames" varchar(255) NULL,
	"EmailAddress" varchar(255) NULL,
	"PhoneNumber" varchar(255) NOT NULL,
	"DateOfBirth" date NOT NULL,
	"JoinedDate" date NULL,
	"Gender" text NOT NULL,
	"ResidentialAddress" varchar(255) NOT NULL,
	"City" varchar(255) NOT NULL,
	"Hometown" varchar(255) NOT NULL,
	"Region" text NOT NULL,
	"GpsAddress" varchar(255) NULL,
	"MaritalStatus" text NOT NULL,
	"NextOfKin" varchar(255) NOT NULL,
	"EmergencyContactName" varchar(255) NOT NULL,
	"EmergencyContactPhoneNumber" varchar(255) NOT NULL,
	"MemberActivityStatus" text NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Members" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Members_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE
);
CREATE INDEX "IX_Members_CongregationId" ON public."Members" USING btree ("CongregationId");
CREATE INDEX "IX_Members_DeletedAt" ON public."Members" USING btree ("DeletedAt");


-- public."Organizations" definition

-- Drop table

-- DROP TABLE public."Organizations";

CREATE TABLE public."Organizations" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"Name" varchar(255) NOT NULL,
	"Description" varchar(255) NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Organizations_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE
);
CREATE INDEX "IX_Organizations_CongregationId" ON public."Organizations" USING btree ("CongregationId");
CREATE UNIQUE INDEX "IX_Organizations_CongregationId_Name" ON public."Organizations" USING btree ("CongregationId", "Name");
CREATE INDEX "IX_Organizations_DeletedAt" ON public."Organizations" USING btree ("DeletedAt");


-- public."ProjectCategories" definition

-- Drop table

-- DROP TABLE public."ProjectCategories";

CREATE TABLE public."ProjectCategories" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"CongregationId" uuid NOT NULL,
	"Name" varchar(255) NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_ProjectCategories" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_ProjectCategories_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE
);
CREATE INDEX "IX_ProjectCategories_CongregationId" ON public."ProjectCategories" USING btree ("CongregationId");
CREATE UNIQUE INDEX "IX_ProjectCategories_CongregationId_Name" ON public."ProjectCategories" USING btree ("CongregationId", "Name");
CREATE INDEX "IX_ProjectCategories_DeletedAt" ON public."ProjectCategories" USING btree ("DeletedAt");


-- public."Projects" definition

-- Drop table

-- DROP TABLE public."Projects";

CREATE TABLE public."Projects" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"CategoryId" int4 NOT NULL,
	"ManagerId" uuid NOT NULL,
	"Name" varchar(255) NOT NULL,
	"TargetAmount" numeric NOT NULL,
	"Status" text NOT NULL,
	"StartDate" date NOT NULL,
	"EndDate" date NULL,
	"Description" varchar(255) NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Projects_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE,
	CONSTRAINT "FK_Projects_Members_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES public."Members"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_Projects_ProjectCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."ProjectCategories"("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_Projects_CategoryId" ON public."Projects" USING btree ("CategoryId");
CREATE INDEX "IX_Projects_CongregationId" ON public."Projects" USING btree ("CongregationId");
CREATE INDEX "IX_Projects_DeletedAt" ON public."Projects" USING btree ("DeletedAt");
CREATE INDEX "IX_Projects_ManagerId" ON public."Projects" USING btree ("ManagerId");


-- public."Tithes" definition

-- Drop table

-- DROP TABLE public."Tithes";

CREATE TABLE public."Tithes" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"MemberId" uuid NOT NULL,
	"Amount" numeric NOT NULL,
	"ForYear" int4 NOT NULL,
	"ForMonth" text NOT NULL,
	"PaymentMethod" text NOT NULL,
	"CollectionDate" date NOT NULL,
	"Description" varchar(255) NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Tithes" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Tithes_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE,
	CONSTRAINT "FK_Tithes_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES public."Members"("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_Tithes_CongregationId" ON public."Tithes" USING btree ("CongregationId");
CREATE INDEX "IX_Tithes_DeletedAt" ON public."Tithes" USING btree ("DeletedAt");
CREATE INDEX "IX_Tithes_MemberId" ON public."Tithes" USING btree ("MemberId");


-- public."TransactionCategories" definition

-- Drop table

-- DROP TABLE public."TransactionCategories";

CREATE TABLE public."TransactionCategories" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"CongregationId" uuid NOT NULL,
	"Name" varchar(255) NOT NULL,
	"CategoryType" text NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_TransactionCategories" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_TransactionCategories_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE
);
CREATE INDEX "IX_TransactionCategories_CongregationId" ON public."TransactionCategories" USING btree ("CongregationId");
CREATE UNIQUE INDEX "IX_TransactionCategories_CongregationId_Name" ON public."TransactionCategories" USING btree ("CongregationId", "Name");
CREATE INDEX "IX_TransactionCategories_DeletedAt" ON public."TransactionCategories" USING btree ("DeletedAt");


-- public."Transactions" definition

-- Drop table

-- DROP TABLE public."Transactions";

CREATE TABLE public."Transactions" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"CategoryId" int4 NOT NULL,
	"TransactionType" text NOT NULL,
	"TransactionDate" date NOT NULL,
	"Amount" numeric NOT NULL,
	"Description" varchar(255) NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Transactions_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE,
	CONSTRAINT "FK_Transactions_TransactionCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."TransactionCategories"("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_Transactions_CategoryId" ON public."Transactions" USING btree ("CategoryId");
CREATE INDEX "IX_Transactions_CongregationId" ON public."Transactions" USING btree ("CongregationId");
CREATE INDEX "IX_Transactions_DeletedAt" ON public."Transactions" USING btree ("DeletedAt");


-- public."Users" definition

-- Drop table

-- DROP TABLE public."Users";

CREATE TABLE public."Users" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"Name" varchar(255) NOT NULL,
	"EmailAddress" varchar(255) NOT NULL,
	"PasswordHash" varchar(255) NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Users_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE
);
CREATE INDEX "IX_Users_CongregationId" ON public."Users" USING btree ("CongregationId");
CREATE INDEX "IX_Users_DeletedAt" ON public."Users" USING btree ("DeletedAt");
CREATE UNIQUE INDEX "IX_Users_EmailAddress" ON public."Users" USING btree ("EmailAddress");


-- public."AttendanceContexts" definition

-- Drop table

-- DROP TABLE public."AttendanceContexts";

CREATE TABLE public."AttendanceContexts" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"CongregationId" uuid NOT NULL,
	"AttendanceTypeId" int4 NOT NULL,
	"Name" varchar(255) NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_AttendanceContexts" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AttendanceContexts_AttendanceTypes_AttendanceTypeId" FOREIGN KEY ("AttendanceTypeId") REFERENCES public."AttendanceTypes"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_AttendanceContexts_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_AttendanceContexts_AttendanceTypeId_Name" ON public."AttendanceContexts" USING btree ("AttendanceTypeId", "Name");
CREATE INDEX "IX_AttendanceContexts_CongregationId" ON public."AttendanceContexts" USING btree ("CongregationId");
CREATE INDEX "IX_AttendanceContexts_DeletedAt" ON public."AttendanceContexts" USING btree ("DeletedAt");


-- public."AttendanceRecords" definition

-- Drop table

-- DROP TABLE public."AttendanceRecords";

CREATE TABLE public."AttendanceRecords" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"AttendanceContextId" int4 NOT NULL,
	"MemberId" uuid NULL,
	"GuestName" varchar(255) NULL,
	"ForDate" date NOT NULL,
	"AttendeeType" text NOT NULL,
	"CheckInTime" time NOT NULL,
	"Description" varchar(255) NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_AttendanceRecords" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AttendanceRecords_AttendanceContexts_AttendanceContextId" FOREIGN KEY ("AttendanceContextId") REFERENCES public."AttendanceContexts"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_AttendanceRecords_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE,
	CONSTRAINT "FK_AttendanceRecords_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES public."Members"("Id") ON DELETE SET NULL
);
CREATE INDEX "IX_AttendanceRecords_AttendanceContextId" ON public."AttendanceRecords" USING btree ("AttendanceContextId");
CREATE INDEX "IX_AttendanceRecords_CongregationId" ON public."AttendanceRecords" USING btree ("CongregationId");
CREATE INDEX "IX_AttendanceRecords_DeletedAt" ON public."AttendanceRecords" USING btree ("DeletedAt");
CREATE INDEX "IX_AttendanceRecords_ForDate" ON public."AttendanceRecords" USING btree ("ForDate");
CREATE INDEX "IX_AttendanceRecords_MemberId" ON public."AttendanceRecords" USING btree ("MemberId");


-- public."Events" definition

-- Drop table

-- DROP TABLE public."Events";

CREATE TABLE public."Events" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"OrganizationId" uuid NOT NULL,
	"OrganizerId" uuid NOT NULL,
	"Name" varchar(255) NOT NULL,
	"StartDate" date NOT NULL,
	"EndDate" date NOT NULL,
	"StartTime" time NULL,
	"EndTime" time NULL,
	"Location" varchar(255) NULL,
	"Capacity" int4 NULL,
	"Description" varchar(255) NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	CONSTRAINT "PK_Events" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Events_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE,
	CONSTRAINT "FK_Events_Members_OrganizerId" FOREIGN KEY ("OrganizerId") REFERENCES public."Members"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_Events_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES public."Organizations"("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_Events_CongregationId" ON public."Events" USING btree ("CongregationId");
CREATE UNIQUE INDEX "IX_Events_CongregationId_Name" ON public."Events" USING btree ("CongregationId", "Name");
CREATE INDEX "IX_Events_DeletedAt" ON public."Events" USING btree ("DeletedAt");
CREATE INDEX "IX_Events_OrganizationId" ON public."Events" USING btree ("OrganizationId");
CREATE INDEX "IX_Events_OrganizerId" ON public."Events" USING btree ("OrganizerId");


-- public."OrganizationMembers" definition

-- Drop table

-- DROP TABLE public."OrganizationMembers";

CREATE TABLE public."OrganizationMembers" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	"MemberId" uuid NOT NULL,
	"OrganizationId" uuid NOT NULL,
	"Role" text NOT NULL,
	"JoinedAt" date NOT NULL,
	CONSTRAINT "PK_OrganizationMembers" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_OrganizationMembers_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE,
	CONSTRAINT "FK_OrganizationMembers_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES public."Members"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_OrganizationMembers_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES public."Organizations"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_OrganizationMembers_CongregationId" ON public."OrganizationMembers" USING btree ("CongregationId");
CREATE INDEX "IX_OrganizationMembers_DeletedAt" ON public."OrganizationMembers" USING btree ("DeletedAt");
CREATE UNIQUE INDEX "IX_OrganizationMembers_MemberId_OrganizationId" ON public."OrganizationMembers" USING btree ("MemberId", "OrganizationId");
CREATE INDEX "IX_OrganizationMembers_OrganizationId" ON public."OrganizationMembers" USING btree ("OrganizationId");


-- public."ProjectContributions" definition

-- Drop table

-- DROP TABLE public."ProjectContributions";

CREATE TABLE public."ProjectContributions" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	"ProjectId" uuid NOT NULL,
	"Amount" numeric NOT NULL,
	"DateContributed" date NOT NULL,
	"PaymentMethod" text NOT NULL,
	"Description" varchar(255) NULL,
	CONSTRAINT "PK_ProjectContributions" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_ProjectContributions_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE,
	CONSTRAINT "FK_ProjectContributions_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES public."Projects"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_ProjectContributions_CongregationId" ON public."ProjectContributions" USING btree ("CongregationId");
CREATE INDEX "IX_ProjectContributions_DeletedAt" ON public."ProjectContributions" USING btree ("DeletedAt");
CREATE INDEX "IX_ProjectContributions_ProjectId" ON public."ProjectContributions" USING btree ("ProjectId");


-- public."EventAttendances" definition

-- Drop table

-- DROP TABLE public."EventAttendances";

CREATE TABLE public."EventAttendances" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	"MemberId" uuid NOT NULL,
	"EventId" uuid NOT NULL,
	"CheckInTime" time NOT NULL,
	CONSTRAINT "PK_EventAttendances" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_EventAttendances_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE,
	CONSTRAINT "FK_EventAttendances_Events_EventId" FOREIGN KEY ("EventId") REFERENCES public."Events"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_EventAttendances_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES public."Members"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_EventAttendances_CongregationId" ON public."EventAttendances" USING btree ("CongregationId");
CREATE INDEX "IX_EventAttendances_DeletedAt" ON public."EventAttendances" USING btree ("DeletedAt");
CREATE UNIQUE INDEX "IX_EventAttendances_EventId_MemberId" ON public."EventAttendances" USING btree ("EventId", "MemberId");
CREATE INDEX "IX_EventAttendances_MemberId" ON public."EventAttendances" USING btree ("MemberId");


-- public."EventRegistrations" definition

-- Drop table

-- DROP TABLE public."EventRegistrations";

CREATE TABLE public."EventRegistrations" (
	"Id" uuid DEFAULT uuidv7() NOT NULL,
	"CongregationId" uuid NOT NULL,
	"CreatedAt" timestamptz DEFAULT now() NOT NULL,
	"DeletedAt" timestamptz NULL,
	"MemberId" uuid NOT NULL,
	"EventId" uuid NOT NULL,
	"RegistrationDate" date NOT NULL,
	CONSTRAINT "PK_EventRegistrations" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_EventRegistrations_Congregations_CongregationId" FOREIGN KEY ("CongregationId") REFERENCES public."Congregations"("CongregationId") ON DELETE CASCADE,
	CONSTRAINT "FK_EventRegistrations_Events_EventId" FOREIGN KEY ("EventId") REFERENCES public."Events"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_EventRegistrations_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES public."Members"("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_EventRegistrations_CongregationId" ON public."EventRegistrations" USING btree ("CongregationId");
CREATE INDEX "IX_EventRegistrations_DeletedAt" ON public."EventRegistrations" USING btree ("DeletedAt");
CREATE UNIQUE INDEX "IX_EventRegistrations_EventId_MemberId" ON public."EventRegistrations" USING btree ("EventId", "MemberId");
CREATE INDEX "IX_EventRegistrations_MemberId" ON public."EventRegistrations" USING btree ("MemberId");