// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

// Members
Table members {
  member_id integer [primary key, increment]
  unique_id uuid [unique]
  first_name varchar(255)
  last_name varchar(255)
  other_names varchar(255)
  email varchar(255) [unique]
  phone_number varchar(16)
  date_of_birth date
  joined_date date
  gender enum
  residential_address varchar(255)
  city varchar(255)
  hometown varchar(255)
  region enum
  gps_address varchar(255)
  marital_status enum
  next_of_kin_name varchar(128)
  emergency_contact_name varchar(128)
  emergency_contact_phone varchar(16)
  is_active bool
}


// Organizations
Table organizations {
  organization_id integer [primary key, increment]
  unique_id uuid [unique]
  name varchar(255)
  description varchar(255)
  created_at date
}

Table organization_members {
  member_id integer [ref: - members.member_id, not null]
  organization_id integer [ref: - organizations.organization_id, not null]
  role enum
  joined_date date

  indexes {
    (member_id, organization_id) [pk]
  }
}


// Attendance
Table service_attendance{
  attendance_id integer [primary key, increment]
  unique_id uuid [unique]
  member_id integer [ref: - members.member_id, null]
  for_date date
  service_type enum [not null]
  role enum
  check_in_time datetime
}


// Events
Table events {
  event_id integer [primary key]
  unique_id uuid [unique]
  organization_id integer [ref: - organizations.organization_id, null]
  organizer_id integer [ref: - members.member_id, null]
  title varchar(255) [not null]
  start_date date
  end_date date
  start_time timestamp [null]
  end_time timestamp [null]
  location varchar(255) [null]
  capacity integer [null]
  description varchar(255) [null]
}

Table event_attendance {
  member_id integer [ref: - members.member_id, not null]
  event_id integer [ref: - events.event_id, not null]
  check_in_time timestamp

  indexes {
    (member_id, event_id) [pk]
  }
}

Table event_registrations {
  member_id integer [ref: - members.member_id, not null]
  event_id integer [ref: - events.event_id, not null]
  unique_id uuid [unique]
  registration_date date

  indexes {
  (member_id, event_id) [pk]
  }
}


// Finances
Table transactions {
  transaction_id integer [primary key]
  unique_id uuid [unique]
  category_id integer [ref: - transaction_categories.category_id]
  transaction_type enum [not null]
  transaction_date date
  amount decimal
  description varchar(255)
}

Table transaction_categories {
  category_id integer [primary key]
  unique_id uuid [unique]
  name varchar(255)
  category_type enum
}


// Tithe
Table tithe {
  tithe_id integer [primary key]
  unique_id uuid [unique]
  member_id integer [ref: - members.member_id, not null]
  amount decimal [not null]
  payment_method enum
  collection_date date [not null]
  forMonth enum [not null]
  forYear integer [not null]
  description varchar(255)
}


// Projects
Table projects {
  project_id integer [primary key]
  unique_key uuid [unique]
  category_id integer [ref: - project_categories.category_id, null]
  project_manager_id integer [ref: - members.member_id, not null]
  project_title varchar(255) [not null]
  target_amount decimal [not null]
  status enum [not null]
  start_date date [null]
  end_date date [null]
  description varchar(255)
}

Table project_categories {
  category_id integer [primary key]
  unique_id uuid [unique]
  name varchar(255) [not null]
}

Table project_contributions {
  contribution_id integer [primary key]
  unique_id uuid [unique]
  project_id integer [ref: - projects.project_id, not null]
  amount decimal [not null]
  date_contributed date
  payment_method enum
  description varchar(255)
}


Table assets {
  asset_id integer [primary key]
  unique_id uuid [unique]
  name varchar(255)
  serial_number varchar(255) [null]
  category_id integer [ref: - asset_categories.category_id, null]
  purchase_date date
  purchase_cost decimal
  current_value decimal
  status enum
  description varchar(255)

  // status can be: in_use, in_storage, under_maintenance, liquidated
  // when an asset is liquidated, we can set the current_value to 0 and status to liquidated
  // we then add a new income to the Assets Sold category in the transactions table with the amount equal
  // to the current_value of the asset
}

Table asset_categories{
  category_id integer [primary key]
  unique_id uuid [unique]
  category_name varchar(255) [not null]
}


/*
  REPORTING
  This table is still a work in progress, it's here because I don't want to forget it and do it again later
*/
Table report_snapshots {
  report_id integer [primary key, increment]
  unique_id uuid [unique]
  report_type enum [not null]
  generated_date datetime
  status enum
  frequency enum [not null]
  period_key varchar (255)
  data_json jsonb

}
