using Echo.Core.Mapping.OrganizationMemberMapping;
using Echo.Core.Tests.TestData.Factories;

namespace Echo.Core.Tests.Mapping.OrganizationMemberMapping;

[Trait("Category", "Unit")]
public class OrganizationMemberMapperTests
{
    private readonly IOrganizationMemberMapper _mapper = new OrganizationMemberMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = OrganizationMemberFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(dto.MemberId, entity.MemberId);
        Assert.Equal(dto.OrganizationId, entity.OrganizationId);
        Assert.Equal(dto.Role, entity.Role);
        Assert.Equal(dto.JoinedAt, entity.JoinedAt);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = OrganizationMemberFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, entity.Id);
        Assert.Equal(Guid.Empty, entity.CongregationId);
        Assert.Null(entity.Congregation);
        Assert.Null(entity.Member);
        Assert.Null(entity.Organization);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = OrganizationMemberFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.MemberId, result.MemberId);
        Assert.Equal(entity.Member.Name, result.MemberName);
        Assert.Equal(entity.OrganizationId, result.OrganizationId);
        Assert.Equal(entity.Organization.Name, result.OrganizationName);
        Assert.Equal(entity.Role, result.Role);
        Assert.Equal(entity.JoinedAt, result.JoinedAt);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void PatchEntity_ShouldPatchSpecifiedFieldsInDto_ToEntity()
    {
        var dto = OrganizationMemberFactory.NewUpdateDto();
        var entity = OrganizationMemberFactory.NewEntity();

        _mapper.Patch(dto, entity);

        Assert.Equal(dto.Role, entity.Role);
        Assert.Equal(dto.JoinedAt, entity.JoinedAt);
    }

    [Fact]
    public void PatchEntity_ShouldIgnoreAllNullFieldsInDto()
    {
        var nullDto = OrganizationMemberFactory.NewUpdateDtoWithNullValues();
        var entity = OrganizationMemberFactory.NewEntity();
        var original = OrganizationMemberFactory.NewEntity();

        _mapper.Patch(nullDto, entity);

        Assert.Equal(original.Role, entity.Role);
        Assert.Equal(original.JoinedAt, entity.JoinedAt);
    }
}
