using Echo.Core.Mapping.TitheMapping;
using Echo.Core.Tests.TestData.Factories;

namespace Echo.Core.Tests.Mapping.TitheMapping;

[Trait("Category", "Unit")]
public class TitheMapperTests
{
    private readonly ITitheMapper _mapper = new TitheMapper();

    [Fact]
    public void ToEntity_ShouldMapAllFields_FromCreateDto()
    {
        var dto = TitheFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(dto.MemberId, entity.MemberId);
        Assert.Equal(dto.Amount, entity.Amount);
        Assert.Equal(dto.ForYear, entity.ForYear);
        Assert.Equal(dto.ForMonth, entity.ForMonth);
        Assert.Equal(dto.PaymentMethod, entity.PaymentMethod);
        Assert.Equal(dto.CollectionDate, entity.CollectionDate);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void ToEntity_ShouldNotOverrideAutoGeneratedIds_FromCreateDto()
    {
        var dto = TitheFactory.NewCreateDto();

        var entity = _mapper.ToEntity(dto);

        Assert.Equal(Guid.Empty, entity.Id);
        Assert.Equal(Guid.Empty, entity.CongregationId);
        Assert.Null(entity.Congregation);
        Assert.Null(entity.Member);
        Assert.Equal(default, entity.CreatedAt);
        Assert.Null(entity.DeletedAt);
    }

    [Fact]
    public void ToDto_ShouldMapAllFields_FromEntity()
    {
        var entity = TitheFactory.NewEntity();

        var result = _mapper.ToDto(entity);

        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.MemberId, result.MemberId);
        Assert.Equal(entity.Member.Name, result.MemberName);
        Assert.Equal(entity.Amount, result.Amount);
        Assert.Equal(entity.ForYear, result.ForYear);
        Assert.Equal(entity.ForMonth, result.ForMonth);
        Assert.Equal(entity.PaymentMethod, result.PaymentMethod);
        Assert.Equal(entity.CollectionDate, result.CollectionDate);
        Assert.Equal(entity.Description, result.Description);
        Assert.Equal(entity.CreatedAt, result.CreatedAt);
    }

    [Fact]
    public void PatchEntity_ShouldPatchSpecifiedFieldsInDto_ToEntity()
    {
        var dto = TitheFactory.NewUpdateDto();
        var entity = TitheFactory.NewEntity();

        _mapper.Patch(dto, entity);

        Assert.Equal(dto.MemberId, entity.MemberId);
        Assert.Equal(dto.Amount, entity.Amount);
        Assert.Equal(dto.ForYear, entity.ForYear);
        Assert.Equal(dto.ForMonth, entity.ForMonth);
        Assert.Equal(dto.PaymentMethod, entity.PaymentMethod);
        Assert.Equal(dto.CollectionDate, entity.CollectionDate);
        Assert.Equal(dto.Description, entity.Description);
    }

    [Fact]
    public void PatchEntity_ShouldIgnoreAllNullFieldsInDto()
    {
        var nullDto = TitheFactory.NewUpdateDtoWithNullValues();
        var entity = TitheFactory.NewEntity();
        var original = TitheFactory.NewEntity();

        _mapper.Patch(nullDto, entity);

        Assert.Equal(original.MemberId, entity.MemberId);
        Assert.Equal(original.Amount, entity.Amount);
        Assert.Equal(original.ForYear, entity.ForYear);
        Assert.Equal(original.ForMonth, entity.ForMonth);
        Assert.Equal(original.PaymentMethod, entity.PaymentMethod);
        Assert.Equal(original.CollectionDate, entity.CollectionDate);
        Assert.Equal(original.Description, entity.Description);
    }
}
