<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc" />
      <PackageReference Include="Resend" />
      <PackageReference Include="System.Security.Cryptography.Xml" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Echo.Application\Echo.Application.csproj" />
      <ProjectReference Include="..\Echo.Core\Echo.Core.csproj" />
    </ItemGroup>

</Project>
